src/Entity/Comment.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\UniqueConstraint;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 * @ORM\Table(uniqueConstraints={@UniqueConstraint(columns={"message", "user_id", "project_id"})})
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1500)
     */
    private $Message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateTile;

    /**
     * @ORM\Column(type="integer")
     */
    private $up;

    /**
     * @ORM\Column(type="integer")
     */
    private $down;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Project", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Project;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }

    public function getDateTile(): ?DateTimeInterface
    {
        return $this->DateTile;
    }

    public function setDateTile(DateTimeInterface $DateTile): self
    {
        $this->DateTile = $DateTile;

        return $this;
    }

    public function getUp(): ?int
    {
        return $this->up;
    }

    public function setUp(int $up): self
    {
        $this->up = $up;

        return $this;
    }

    public function getDown(): ?int
    {
        return $this->down;
    }

    public function setDown(int $down): self
    {
        $this->down = $down;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->Project;
    }

    public function setProject(?Project $Project): self
    {
        $this->Project = $Project;

        return $this;
    }

    public function __toString()
    {
        return $this->getMessage();
    }
}

src/Entity/Reward.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RewardRepository")
 */
class Reward
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $Level;

    /**
     * @ORM\Column(type="string", length=1500)
     */
    private $Description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Project", inversedBy="rewards")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Project;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getProject() . " reach " . $this->getLevel();
    }

    public function getProject(): ?Project
    {
        return $this->Project;
    }

    public function setProject(?Project $Project): self
    {
        $this->Project = $Project;

        return $this;
    }

    public function getLevel(): ?float
    {
        return $this->Level;
    }

    public function setLevel(float $Level): self
    {
        $this->Level = $Level;

        return $this;
    }

}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Project;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title')
            ->add('Goal', MoneyType::class, [
                'required' => true,
            ])
            ->add('LimitDate', DateType::class, [
                'widget' => 'choice',
                'years' => range(date('Y'), date('Y') + 10),
                'months' => range(0, 12),
                'days' => range(0, 31),
                'required' => true,
            ])
            ->add('Description', CKEditorType::class, [
                'required' => true,
            ])
            ->add('Miniature', TextType::class, [
                'required' => true
            ])
            ->add('categories', EntityType::class, ['class' => Category::class, 'multiple' => true,
                'expanded' => true,]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Project;
use App\Entity\Subscription;
use App\Entity\User;
use App\Form\CommentType;
use App\Form\ProjectType;
use App\Repository\CategoryRepository;
use App\Repository\ProjectRepository;
use App\Repository\StatusRepository;
use DateTime;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/project")
 */
class ProjectController extends AbstractController
{
    /**
     * @Route("/", name="project_index", methods={"GET"})
     * @param ProjectRepository $projectRepository
     * @param CategoryRepository $categoryRepository
     * @return Response
     */
    public function index(ProjectRepository $projectRepository, CategoryRepository $categoryRepository): Response
    {
        return $this->render('project/index.html.twig', [
            'projects' => $projectRepository->findAll(),
            'CloseProjects' => $projectRepository->findClosedToBeFinanced(),
            'Category' => $categoryRepository->findAll(),
            'LovedProjects' => $projectRepository->findMostLoved()
        ]);
    }

    /**
     * @Route("/new", name="project_new", methods={"GET","POST"})
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @param Request $request
     * @param StatusRepository $statusRepository
     * @return Response
     */
    public function new(Request $request, StatusRepository $statusRepository): Response
    {
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $project->setUser($this->getUser());
            $project->setStatu($statusRepository->findAll()[0]);
            $project->setReport(0);
            $entityManager->persist($project);
            $entityManager->flush();
            return $this->redirectToRoute('project_index');
        }

        return $this->render('project/new.html.twig', [
            'project' => $project,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="project_show", methods={"GET", "POST"})
     * @param Project $project
     * @param Request $request
     * @return Response
     */
    public function show(Project $project, Request $request): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        $comment->setUser($this->getUser())
            ->setUp(0)
            ->setProject($project)
            ->setDown(0)
            ->setDateTile(new DateTime('NOW'));

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();
            return $this->redirectToRoute('project_show', ['id' => $project->getId()]);
        }
        return $this->render('project/show.html.twig', [
            'project' => $project,
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="project_edit", methods={"GET","POST"})
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @param Request $request
     * @param Project $project
     * @return Response
     */
    public function edit(Request $request, Project $project): Response
    {
        if ($this->getUser() === $project->getUser()) {
            $form = $this->createForm(ProjectType::class, $project);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $this->getDoctrine()->getManager()->flush();

                return $this->redirectToRoute('project_index');
            }

            return $this->render('project/edit.html.twig', [
                'project' => $project,
                'form' => $form->createView(),
            ]);
        } else {
            return $this->render('project/show.html.twig', [
                'project' => $project,
            ]);
        }
    }

    /**
     * @Route("/{id}", name="project_delete", methods={"DELETE"})
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @param Request $request
     * @param Project $project
     * @return Response
     */
    public function delete(Request $request, Project $project): Response
    {
        if ($this->getUser() === $project->getUser()) {
            if ($this->isCsrfTokenValid('delete' . $project->getId(), $request->request->get('_token'))) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->remove($project);
                $entityManager->flush();
            }

            return $this->redirectToRoute('project_index');
        } else {
            return $this->render('project/show.html.twig', [
                'project' => $project,
            ]);
        }
    }

    /**
     * @Route("/{id}/like", name="project_like", methods={"GET","POST"})
     * @param Project $project
     * @return Response
     */
    public function like(Project $project): Response
    {
        /** @var User $user */
        $user = $this->getDoctrine()->getManager()->getRepository(User::class)->findOneBy(['username' => $this->getUser()->getUsername()]);
        $project->addLikep($user);
        $project->removeDislike($user);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->flush();
        return $this->render('API/bin.html.twig');
    }

    /**
     * @Route("/{id}/unlike", name="project_unlike", methods={"GET","POST"})
     * @param Project $project
     * @return Response
     */
    public function unLike(Project $project): Response
    {
        /** @var User $user */
        $user = $this->getDoctrine()->getManager()->getRepository(User::class)->findOneBy(['username' => $this->getUser()->getUsername()]);
        $project->removeLike($user);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->flush();
        return $this->render('API/bin.html.twig');
    }

    /**
     * @Route("/{id}/dislike", name="project_dislike", methods={"GET","POST"})
     * @param Project $project
     * @return Response
     */
    public function dislike(Project $project): Response
    {
        /** @var User $user */
        $user = $this->getDoctrine()->getManager()->getRepository(User::class)->findOneBy(['username' => $this->getUser()->getUsername()]);
        $project->addDislike($user);
        $project->removelike($user);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->persist($project);
        $entityManager->flush();
        return $this->render('API/bin.html.twig');
    }

    /**
     * @Route("/{id}/undislike", name="project_undislike", methods={"GET","POST"})
     * @param Project $project
     * @return Response
     */
    public function unDislike(Project $project): Response
    {
        /** @var User $user */
        $user = $this->getDoctrine()->getManager()->getRepository(User::class)->findOneBy(['username' => $this->getUser()->getUsername()]);
        $project->removeDislike($user);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->persist($project);
        $entityManager->flush();
        return $this->render('API/bin.html.twig');
    }

    /**
     * @Route("/{id}/sub", name="project_sub", methods={"GET","POST"})
     * @param Project $project
     * @return Response
     */
    public function subscribe(Project $project): Response
    {
        $project->addSubscribe($this->getDoctrine()->getManager()->getRepository(User::class)->findOneBy(['username' => $this->getUser()->getUsername()]));
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($project);
        $entityManager->flush();
        return $this->render('API/bin.html.twig');
    }

    /**
     * @Route("/{id}/unsub", name="project_unsub", methods={"GET","POST"})
     * @param Project $project
     * @return Response
     */
    public function unSubscribe(Project $project): Response
    {
        $project->removeSubscribe($this->getDoctrine()->getManager()->getRepository(User::class)->findOneBy(['username' => $this->getUser()->getUsername()]));
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($project);
        $entityManager->flush();
        return $this->render('API/bin.html.twig');
    }
}

templates/project/_delete_form.html.twig
<form method="post" action="{{ path('project_delete', {'id': project.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
    <button class="btn btn-danger">{% trans %}Delete{% endtrans %}</button>
</form>

templates/project/_form.html.twig
{% form_theme form 'bootstrap_4_horizontal_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-primary btn-lg">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/project/_project_card.html.twig
<div class="col-lg-4 col-md-6 mb-4 ml-auto mr-auto" style="min-width: 400px;">
    <div class="card h-100 p-1">
        <a class="h-50 d-flex" href="{{ path('project_show', {'id': project.id}) }}"><img class="card-img m-auto mh-100"
                                                                                          src="{{ project.miniature }}"
                                                                                          alt="miniature of {{ project.title }}"></a>
        <div class="progress">
            <div class="progress-bar bg-warning" role="progressbar"
                 style="width: {{ (project.goal - project.rest) / project.goal * 100 }}%"
                 aria-valuenow="{{ (project.goal - project.rest) / project.goal * 100 }}" aria-valuemin="0"
                 aria-valuemax="100"></div>
        </div>
        <div class="card-body h-50">
            <h4 class="card-title">
                <a href="{{ path('project_show', {'id': project.id}) }}">{{ project.title|striptags|length > 25 ?  project.title|striptags|slice(0, 20) ~ '...' :  project.title|striptags }}</a>
            </h4>
            <h5 class="card-text">{{ (project.goal - project.rest)|number_format(2, ',', ' ') }}
                / {{ project.goal|number_format(2, ',', ' ') }}€</h5>
            <div class="d-inline-block w-100">
                <div class="d-inline-flex">
                    {% if is_granted('ROLE_USER') %}
                        <div class="d-inline-flex">
                            {% if app.user.isProjectLiked(project) %}
                                <i data-id="{{ project.id }}" data-up="1"
                                   data-url="{{ path('project_unlike', {'id': project.id}) }}"
                                   class="unup socia fas fa-thumbs-up text-primary"></i>
                            {% else %}
                                <i data-id="{{ project.id }}" data-up="1"
                                   data-url="{{ path('project_like', {'id': project.id}) }}"
                                   class="up fas socia fa-thumbs-up"></i>
                            {% endif %}
                            <p class="upNB">{{ project.likep.count|number_format(0, ',', ' ') }}</p>
                        </div>

                        {% if app.user.isProjectDisliked(project) %}
                            <i data-id="{{ project.id }}" data-up="0"
                               data-url="{{ path('project_undislike', {'id': project.id}) }}"
                               class="undown socia fas fa-thumbs-down text-danger"></i>
                        {% else %}
                            <i data-id="{{ project.id }}" data-up="0"
                               data-url="{{ path('project_dislike', {'id': project.id}) }}"
                               class="down socia fas fa-thumbs-down"></i>
                        {% endif %}

                        <p class="downNB">{{ project.down|number_format(0, ',', ' ') }}</p>
                        {% if app.user.isProjectSubscribe(project) %}
                            <i data-up="2" class="unsub socia fas fa-bookmark text-info"
                               data-url="{{ path('project_unsub', {'id': project.id}) }}"></i>
                        {% else %}
                            <i data-up="2" class="sub socia fas fa-bookmark"
                               data-url="{{ path('project_sub', {'id': project.id}) }}"></i>
                        {% endif %}
                    {% else %}
                        <div class="d-inline-flex">
                            <a onclick="alert('{% trans %}You need to be authenticated for make this action{% endtrans %}')"><i
                                        class="fas socia fa-thumbs-up"
                                        onclick="alert('{% trans %}You need to be authenticated for make this action{% endtrans %}')"></i></a>
                            <p>{{ project.up }}</p>
                        </div>
                        <div class="d-inline-flex">
                            <a onclick="alert('{% trans %}You need to be authenticated for make this action{% endtrans %}')"><i
                                        class="fas socia fa-thumbs-down"></i></a>
                            <p onclick="alert('{% trans %}You need to be authenticated for make this action{% endtrans %}')">{{ project.down }}</p>
                        </div>
                        <a onclick="alert('{% trans %}You need to be authenticated for make this action{% endtrans %}')"><i
                                    class="fas socia fa-bookmark"></i></a>
                    {% endif %}
                </div>
                <div class="w-100 card-tex">
                    {% if (project.goal - project.rest) / project.goal * 100 >= 100 %}
                        <img class="float-right mb-0" src="{{ asset('Resources/Logo.svg') }}" alt="pingouin"
                             style="width: 50px;">
                    {% elseif (project.goal - project.rest) / project.goal * 100 < 50 %}
                        <img class="float-right mb-0" src="{{ asset('Resources/bebe_pingouin.svg') }}" alt="pingouin"
                             style="width: 50px;">
                    {% elseif (project.goal - project.rest) / project.goal * 100 >= 50 %}
                        <img class="float-right mb-0" src="{{ asset('Resources/ado_pingouin.svg') }}" alt="pingouin"
                             style="width: 50px;">
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-footer">
            <small class="text-muted d-inline-flex">
                {% for i in 0..4 %}
                    {% if i < ((5*(project.likep|length / (project.dislike|length + 1)))|round) %}
                        <p class="text-warning">&#9733;</p>
                    {% else %}
                        <p>&#9734;</p>
                    {% endif %}
                {% endfor %}</small>
        </div>
    </div>
</div>

templates/project/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Edit Project{% endtrans %}{% endblock %}

{% block body %}
    <h1>{% trans %}Edit Project{% endtrans %}</h1>

    {{ include('project/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('project_index') }}" class="btn btn-primary" style="margin-left: 1.5em">{% trans %}back to list{% endtrans %}</a>

    {{ include('project/_delete_form.html.twig') }}
{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}All project to support{% endtrans %}{% endblock %}

{% block body %}
<!-- Page Content -->
<div class="container-fluid">
    <div class="row">
        <div class="w-100">
            <div id="carouselExampleIndicators" class="carousel slide my-4 w-100 d-flex" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for i in 0..2 %}
                        {% if i == 0 %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        {% else %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ i }}"></li>
                        {% endif %}
                    {% endfor %}
                </ol>
                <div class="carousel-inner d-flex m-auto" role="listbox" style="height: 500px;">
                    {% for i in 0..2 %}
                        {% if i == 0 %}
                            <div class="carousel-item active m-auto">
                                <a href="{{ path('project_show', {'id': LovedProjects[i].id }) }}"><img
                                            class="d-block img-fluid m-auto" src="{{ LovedProjects[i].miniature }}"
                                            alt="First slide"></a>
                            </div>
                        {% else %}
                            <div class="carousel-item m-auto">
                                <a href="{{ path('project_show', {'id': LovedProjects[i].id }) }}"><img
                                            class="d-block img-fluid m-auto" src="{{ LovedProjects[i].miniature }}"
                                            alt="slide"></a>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <article class="projectArticle">
                <div class="d-inline-flex">
                    <h2>{% trans %}Close to be financed{% endtrans %}</h2>
                    <a href="{{ path('donation_new') }}"
                       class="btn btn-bg-secondary ml-3">{% trans %}Donate{% endtrans %}</a>
                </div>
                <div class="closedProjects projectContainer">
                    {% for project in CloseProjects %}
                        {{ include('project/_project_card.html.twig') }}
                    {% endfor %}
                </div>
                <div class="d-inline-flex">
                    <h2>{% trans %}Most loved projects{% endtrans %}</h2>
                    <a href="{{ path('donation_new') }}"
                       class="btn btn-bg-secondary ml-3">{% trans %}Donate{% endtrans %}</a>
                </div>
                <div class="lovedProjects projectContainer">

                    {% for project in LovedProjects %}
                        {{ include('project/_project_card.html.twig') }}
                    {% endfor %}
                </div>
            </article>
        </div>
        {{ include('category/_list_cat.html.twig') }}
    </div>
</div>
{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Project{% endtrans %}{% endblock %}

{% block body %}

    <!-- Page Content -->
    <div class="container-fluid">

        <div class="row">
            <!-- Post Content Column -->
            <div class="col-lg-8">
                <!-- Title -->
                <h1 class="mt-4">{{ project.title }}</h1>
                <!-- Author -->
                <p class="lead">
                    {% trans %}by{% endtrans %}
                    <a href="{{ path('user_show', {'id' : project.user.id}) }}">{{ project.user }}</a>
                </p>
                <hr>
                <!-- Date/Time -->
                <p>{% trans %}Funding limit{% endtrans %}
                    : {{ project.limitDate|format_datetime('short', 'none', locale=app.request.locale) }}</p>
                <hr>
                <!-- Preview Image -->
                <div>
                    <img class="img-fluid rounded w-100" src="{{ project.miniature }}" alt="project miniature">
                    <div class="progress mt-3">
                        <div class="progress-bar bg-warning" role="progressbar"
                             style="width: {{ (project.goal - project.rest) / project.goal * 100 }}%"
                             aria-valuenow="{{ (project.goal - project.rest) / project.goal * 100 }}"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    {% if  (project.goal - project.rest) / project.goal  >= 1 %}
                        <h2 class="text-success text-center">{% trans %}100% FUNDED !{% endtrans %}</h2>
                    {% endif %}
                </div>
                <hr>

                <!-- Post Content -->
                <p class="mr-3">
                    <a class="btn btn-primary w-100" data-toggle="collapse" href="#collapseExample" role="button"
                       aria-expanded="false" aria-controls="collapseExample">
                        {% trans %}Description{% endtrans %} <i class="fas fa-arrow-circle-down"></i>
                    </a>
                </p>
                <div class="collapse" id="collapseExample">
                    <div class="card card-body d-inline-block">
                        <p class="lead">{{ project.description|raw }}</p>
                    </div>
                </div>

                <hr>

                <!-- Comments Form -->
                <div class="card my-4">
                    <h5 class="card-header">{% trans %}Leave a Comment{% endtrans %}:</h5>
                    <div class="card-body d-flex">
                        {{ include('comment/_form.html.twig') }}
                    </div>
                </div>

                {% for comment in project.comments %}
                    <div class="media mb-4">
                        <img class="d-flex mr-3 rounded-circle" width="50px" height="50px"
                             src="{{ asset('Resources/Logo.svg') }}" alt="">
                        <div class="media-body bg-light p-3">
                            <div class="d-inline-flex">
                                <h5 class="mt-0 mr-3">{{ comment.user }}</h5>
                                <h6>{{ comment.dateTile|format_datetime( locale=app.request.locale) }}</h6>
                            </div>
                            <hr>
                            {{ comment.message }}
                        </div>
                    </div>
                {% endfor %}
            </div>

            <!-- Sidebar Widgets Column -->
            <div class="col-md-3">

                <!-- Categories Widget -->
                <div class="card my-4">
                    <h5 class="card-header">{% trans %}Categories of project{% endtrans %}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <ul class="list-unstyled mb-0">
                                    {% for cat in project.categories %}
                                        <li>
                                            <a href="{{ path('category_show', {'id': cat.id}) }}">{{ cat }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Side Widget -->
                <!-- état du financement -->
                <div class="card my-4">
                    <h5 class="card-header">{% trans %}Funding advancement{% endtrans %}</h5>
                    <div class="card-body">
                        <p class="card-text">{% trans %}This project is{% endtrans %} {{ project.statu }}</p>
                        <div class="progress">
                            <div class="progress-bar bg-warning" role="progressbar"
                                 style="width: {{ (project.goal - project.rest) / project.goal * 100 }}%"
                                 aria-valuenow="{{ (project.goal - project.rest) / project.goal * 100 }}"
                                 aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p class="card-text">{{ (project.goal - project.rest)|number_format(2, ',', ' ') }}
                            / {{ project.goal|number_format(2, ',', ' ') }} €</p>
                        <p class="card-text">{% trans %}This project need{% endtrans %} {{ project.rest|number_format(2, ',', ' ') }}
                            € {% trans %}before{% endtrans %} {{ project.limitDate|format_datetime(locale=app.request.locale) }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    {% if project.user == app.user %}
        <a href="{{ path('project_edit', {'id': project.id}) }}"
           class="btn btn-primary">{% trans %}edit{% endtrans %}</a>
    {% endif %}
    <a href="{{ path('project_index') }}" class="btn btn-primary"
       style="margin-left: 0.5em">{% trans %}back to list{% endtrans %}</a>

{% endblock %}